//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOD_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDtl
    {
        public int id { get; set; }
        public string txtType { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> mentorId { get; set; }
        public Nullable<int> skillId { get; set; }
        public string skillName { get; set; }
        public string fees { get; set; }
        public string mentorfees { get; set; }
        public string commision { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
    }
}
